  
version: '2.1'

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack-light
    ports:
      - "4566-4599:4566-4599"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3,ec2,apigateway,lambda,iam,dynamodb,sns,sqs
      - DEBUG=1
      - DATA_DIR=/data
      - PORT_WEB_UI=${PORT_WEB_UI- 8080}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR}
    volumes:
      - "${TMPDIR:-/c/Users/abhik/Documents/Docker-apps/localstack/data}:/tmp/localstack"
      #- "/var/run/docker.sock:/var/run/docker.sock"