version: '3'

services: 
    mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        environment: 
            ACCEPT_EULA: Y
            SA_PASSWORD: Password(!)
        ports: 
            - "1433:1433"
        #volumes: 
            #- "//C/Users/abhik/Documents/Docker-apps/mssql/data:/var/opt/mssql/data"